=== CailanJB/CSE305-A2/lib/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "title": "Adventure Schema for CSE 305/505 2026 Fall",
    "type": "object",
    "properties": {
        "rooms": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/room"
            }
        },
        "items": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/item"
            }
        },
        "start": {
            "type": "number"
        },
        "starting_inventory": {
            "type": "array",
            "items": {
                "type": "number"
            }
        },
        "item_locs": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "item_id": {
                        "type": "number"
                    },
                    "room_id": {
                        "type": "number"
                    }
                }
            }
        },
        "winning_message": {
            "type": "string"
        }
    },
    "$defs": {
        "roomdesc": {
            "type": "object",
            "properties": {
                "room_items": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "inv_items": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "desc": {
                    "type": "string"
                }
            }
        },
        "exit": {
            "type": "object",
            "properties": {
                "direction": {
                    "type": "string"
                },
                "room": {
                    "type": "number"
                },
                "to_unlock": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                }
            }
        },
        "room": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "number"
                },
                "descs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/roomdesc"
                    }
                },
                "points": {
                    "type": "number"
                },
                "exits": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/exit"
                    }
                },
                "to_drop": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                }
            }
        },
        "item": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "id": {
                    "type": "number"
                },
                "desc": {
                    "type": "string"
                },
                "points": {
                    "type": "number"
                }
            }
        }
    }
}

=== CailanJB/CSE305-A2/example_games/small_circle.json
{
    "rooms": [
        {
            "id": 0,
            "descs": [
                {
                    "room_items": [
                        0,
                        1
                    ],
                    "inv_items": [],
                    "desc": "You're no longer in the small circle. You escaped."
                },
                {
                    "room_items": [],
                    "inv_items": [
                        0,
                        1
                    ],
                    "desc": "You're back in the room you started in. The gems in your hands start to glow and vibrate. It's as if they want to be placed in the slots on the altar in front of you."
                },
                {
                    "room_items": [],
                    "inv_items": [],
                    "desc": "You find yourself in a small room. There is an altar in the middle with two slots, one square and one circle. A closed door reads \"exit\". Two open doors lead to two rooms, each seemingly empty except for a shine in the middle of the floor."
                }
            ],
            "points": 0,
            "exits": [
                {
                    "direction": "onward",
                    "room": 1,
                    "to_unlock": []
                },
                {
                    "direction": "back",
                    "room": 2,
                    "to_unlock": []
                }
            ],
            "to_drop": [
                0,
                1
            ]
        },
        {
            "id": 1,
            "descs": [
                {
                    "room_items": [
                        0
                    ],
                    "inv_items": [],
                    "desc": "In front of you lays a small circular gem. There are two doors: one to the room with an altar, and another to a third room."
                },
                {
                    "room_items": [],
                    "inv_items": [],
                    "desc": "This is where you found the circular gem. There are two doors: one to the room with an altar, and another to a third room."
                }
            ],
            "points": 0,
            "exits": [
                {
                    "direction": "back",
                    "room": 0,
                    "to_unlock": []
                },
                {
                    "direction": "onward",
                    "room": 2,
                    "to_unlock": []
                }
            ],
            "to_drop": []
        },
        {
            "id": 2,
            "descs": [
                {
                    "room_items": [],
                    "inv_items": [],
                    "desc": "This is where you found the square gem. There are two doors: one to the room with an altar, and another to a third room."
                },
                {
                    "room_items": [],
                    "inv_items": [
                        1
                    ],
                    "desc": "In front of you lays a small square gem. There are two doors: one to the room with an altar, and another to a third room."
                }
            ],
            "points": 0,
            "exits": [
                {
                    "direction": "altar",
                    "room": 0,
                    "to_unlock": []
                },
                {
                    "direction": "back",
                    "room": 1,
                    "to_unlock": []
                }
            ],
            "to_drop": []
        }
    ],
    "items": [
        {
            "name": "Circular Gem",
            "id": 0,
            "desc": "A small circular gem. It looks like it would fit into the altar in the first room.",
            "points": 50
        },
        {
            "name": "Square Gem",
            "id": 1,
            "desc": "A small square gem. It looks like it would fit into the altar in the first room.",
            "points": 50
        }
    ],
    "start": 0,
    "starting_inventory": [],
    "item_locs": [
        {
            "item_id": 0,
            "room_id": 1
        },
        {
            "item_id": 1,
            "room_id": 2
        }
    ],
    "winning_message": "As you place the second gem in the altar, the room rumbles as the closed door opens. You step outside and breathe in the fresh air. You still don't know how you got there, but you managed to escape."
}

=== CailanJB/CSE305-A2/example_games/one_room.json
{
    "rooms": [
        {
            "id": 0,
            "descs": [
                {
                    "room_items": [],
                    "inv_items": [],
                    "desc": "The only room in this adventure."
                }
            ],
            "points": 0,
            "exits": [],
            "to_drop": []
        }
    ],
    "items": [],
    "start": 0,
    "starting_inventory": [],
    "item_locs": [],
    "winning_message": "You won!"
}

=== CailanJB/CSE305-A2/example_games/two_rooms.json
{
    "rooms": [
        {
            "id": 0,
            "descs": [
                {
                    "room_items": [],
                    "inv_items": [],
                    "desc": "The first room in this adventure."
                }
            ],
            "points": 0,
            "exits": [
                {
                    "direction": "other",
                    "room": 1,
                    "to_unlock": []
                }
            ],
            "to_drop": []
        },
        {
            "id": 1,
            "descs": [
                {
                    "room_items": [],
                    "inv_items": [],
                    "desc": "The second room in this adventure."
                }
            ],
            "points": 1,
            "exits": [
                {
                    "direction": "first",
                    "room": 0,
                    "to_unlock": []
                }
            ],
            "to_drop": []
        }
    ],
    "items": [],
    "start": 0,
    "starting_inventory": [],
    "item_locs": [],
    "winning_message": "You win the two-room adventure! Thanks for playing."
}
